'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EasyHost.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property apk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("apk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property audio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property console() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("console", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property download() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property DwService() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("DwService", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Error_512__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Error_512__1_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property exe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property file() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("file", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html class=&quot;&quot; lang=&quot;ar&quot;&gt;
        ''' &lt;head&gt;
        '''  &lt;meta charset=&quot;utf-8&quot;/&gt;
        '''  &lt;meta content=&quot;IE=edge&quot; http-equiv=&quot;X-UA-Compatible&quot;/&gt;
        '''  &lt;meta content=&quot;width=device-width, initial-scale=1.0&quot; name=&quot;viewport&quot;/&gt;
        '''  &lt;link href=&quot;https://fonts.googleapis.com&quot; rel=&quot;preconnect&quot;/&gt;
        '''  &lt;link crossorigin=&quot;&quot; href=&quot;https://fonts.gstatic.com&quot; rel=&quot;preconnect&quot;/&gt;
        '''  &lt;link href=&quot;css2?family=Raleway:wght@100;200;400;600;800&amp;amp;display=swap&quot; rel=&quot;stylesheet&quot;/&gt;
        '''  &lt;title&gt;
        '''   اختبار الذكاء عبر الإنترنت - تقييم دقيق للدرجة ا [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property iqar() As String
            Get
                Return ResourceManager.GetString("iqar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        ''' &lt;head&gt;
        '''  &lt;script&gt;
        '''   window.dataLayer = window.dataLayer || [];
        '''  &lt;/script&gt;
        '''  &lt;meta charset=&quot;utf-8&quot;/&gt;
        '''  &lt;title&gt;
        '''   Take the IQ Test and discover your IQ today
        '''  &lt;/title&gt;
        '''  &lt;link href=&quot;https://brght.org/&quot; rel=&quot;canonical&quot;/&gt;
        '''[metacnt]
        '''  &lt;meta content=&quot;width=device-width, initial-scale=1&quot; name=&quot;viewport&quot;/&gt;
        '''  &lt;link crossorigin=&quot;anonymous&quot; href=&quot;npm/bootstrap@5.2.2/dist/css/bootstrap.min.css&quot; integrity=&quot;sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi&quot; r [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property iqen() As String
            Get
                Return ResourceManager.GetString("iqen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property krz() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("krz", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;meta name=&quot;description&quot; content=&quot;[desc]&quot;&gt; &lt;link rel=&quot;amphtml&quot; href=&quot;https://storyzink.com/index.amp.o.html&quot;&gt;
        '''&lt;meta property=&quot;og:title&quot; content=&quot;[title]&quot;&gt;
        '''&lt;meta property=&quot;og:site_name&quot; content=&quot;[sitename]&quot;&gt;
        '''&lt;meta property=&quot;og:url&quot; content=&quot;[url]&quot;&gt;
        '''&lt;meta property=&quot;og:description&quot; content=&quot;[ogdesc]&quot;&gt;
        '''&lt;meta property=&quot;og:type&quot; content=&quot;website&quot;&gt;
        '''&lt;meta property=&quot;og:image&quot; content=&quot;[image]&quot;&gt;.
        '''</summary>
        Friend ReadOnly Property Metainfo() As String
            Get
                Return ResourceManager.GetString("Metainfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mute() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mute", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nfound() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nfound", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property notification() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("notification", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property powerpoint() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("powerpoint", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property python() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("python", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&quot;en&quot;&gt;
        '''&lt;head&gt;
        '''&lt;script src=&quot;/cdn-cgi/apps/head/XrOjnlaGWlWFCsVvC73HZ0HinlY.js&quot;&gt;&lt;/script&gt;&lt;script&gt;
        '''    function getCookie(cname) {
        '''        var name = cname + &quot;=&quot;;
        '''        var decodedCookie = decodeURIComponent(document.cookie);
        '''        var ca = decodedCookie.split(&apos;;&apos;);
        '''        for (var i = 0; i &lt; ca.length; i++) {
        '''            var c = ca[i];
        '''            while (c.charAt(0) == &apos; &apos;) {
        '''                c = c.substring(1);
        '''            }
        '''            if (c.indexOf(name) == 0) {
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property sarahahEN() As String
            Get
                Return ResourceManager.GetString("sarahahEN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&quot;ar&quot;&gt;
        ''' &lt;head&gt;
        '''  &lt;meta charset=&quot;utf-8&quot; content=&quot;text/html&quot; http-equiv=&quot;content-type&quot;/&gt;
        '''  &lt;meta content=&quot;IE=Edge&quot; http-equiv=&quot;X-UA-Compatible&quot;/&gt;
        '''  &lt;meta content=&quot;width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no&quot; name=&quot;viewport&quot;/&gt;
        '''  &lt;title&gt;
        '''   Samira - Saraahah | صراحة
        '''  &lt;/title&gt;
        '''  &lt;link href=&quot;upload/general/logo_thumb.png&quot; rel=&quot;icon&quot; sizes=&quot;96x96&quot; type=&quot;image/png&quot;/&gt;
        '''  &lt;link href=&quot;https://saraahah.com&quot; hreflang=&quot;ar&quot; rel=&quot;alternate&quot;&gt;
        '''&lt;script type=&quot;text [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property sarahahv1() As String
            Get
                Return ResourceManager.GetString("sarahahv1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        ''' &lt;head&gt;
        '''  &lt;meta charset=&quot;utf-8&quot;/&gt;
        '''  &lt;meta content=&quot;width=device-width, initial-scale=1&quot; name=&quot;viewport&quot;/&gt;
        '''  &lt;link href=&quot;favicon.ico&quot; rel=&quot;shortcut icon&quot; type=&quot;image/x-icon&quot;/&gt;
        '''  &lt;link href=&quot;favicon.ico&quot; rel=&quot;icon&quot; type=&quot;image/x-icon&quot;/&gt;
        '''  &lt;title&gt;
        '''   ØµØ§Ø±Ø­Ù†ÙŠ Ø¨Ø±Ø³Ø§Ù„Ø© Ø³Ø±ÙŠØ© Samira moalla
        '''  &lt;/title&gt;
        '''[metacnt]
        '''  &lt;meta content=&quot;website&quot; property=&quot;og:type&quot;/&gt;
        ''' &lt;meta content=&quot;737&quot; property=&quot;og:image:width&quot;/&gt;
        '''  &lt;meta content=&quot;384&quot; property=&quot;og:image:height&quot;/&gt;
        ''' 
        '''  &lt;scri [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property sarahahv2() As String
            Get
                Return ResourceManager.GetString("sarahahv2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;!--[if lt IE 7]&gt;&lt;html class=&quot;no-js lt-ie9 lt-ie8 lt-ie7&quot; lang=&quot;en&quot;&gt; &lt;![endif]--&gt;
        '''&lt;!--[if IE 7]&gt;&lt;html class=&quot;no-js lt-ie9 lt-ie8&quot; lang=&quot;en&quot;&gt; &lt;![endif]--&gt;
        '''&lt;!--[if IE 8]&gt;&lt;html class=&quot;no-js lt-ie9&quot; lang=&quot;en&quot;&gt; &lt;![endif]--&gt;
        '''&lt;!--[if IE 9 ]&gt;&lt;html class=&quot;ie9 no-js&quot;&gt; &lt;![endif]--&gt;
        '''&lt;!--[if (gt IE 9)|!(IE)]&gt;&lt;!--&gt;
        '''&lt;html class=&quot;no-js&quot;&gt;
        ''' &lt;!--&lt;![endif]--&gt;
        ''' &lt;head&gt;
        '''  &lt;!-- Basic page needs ================================================== --&gt;
        '''  &lt;meta charset=&quot;utf-8&quot;/&gt;
        '''  &lt;meta content=&quot;IE=edge,chrom [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property sexmag() As String
            Get
                Return ResourceManager.GetString("sexmag", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property tsweb() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("tsweb", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property word() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("word", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property zip() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zip", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
